export const ShiftReducerConstants = {
	GET_DATA: "GETDATA",
	MYSHIFTS: "MYSHIFTS",
	AVAILABLE_SHIFTS: "AVAILABLESHIFTS",
	ERROR: "ERROR",
	LOADING: "LOADING",
	CANCEL_SHIFT: "CANCEL_SHIFT",
	BOOK_SHIFT: "BOOK_SHIFT",
};
